from flask import Blueprint

from app.controllers import admin_controller

admin_bp = Blueprint("admin", __name__, url_prefix="/admin")

admin_bp.add_url_rule("/action", view_func=admin_controller.perform_action, methods=["POST"])
admin_bp.add_url_rule("/panel", view_func=admin_controller.overview, methods=["GET"])
admin_bp.add_url_rule("/logistica-edecanes", view_func=admin_controller.usher_logistics_page, methods=["GET"])
admin_bp.add_url_rule("/integracion-regional", view_func=admin_controller.regional_integration_page, methods=["GET", "POST"])
admin_bp.add_url_rule("/asignaciones", view_func=admin_controller.assignments_page, methods=["GET"])
admin_bp.add_url_rule(
    "/jueces/evaluacion/whatsapp/<int:judge_id>/enviado",
    view_func=admin_controller.mark_whatsapp_reminder_sent,
    methods=["POST"],
)
admin_bp.add_url_rule("/asignaciones/cupo-presencial", view_func=admin_controller.exposition_capacity_page, methods=["GET", "POST"])
admin_bp.add_url_rule("/asignaciones/cupo-presencial/excel", view_func=admin_controller.exposition_capacity_excel, methods=["GET", "POST"])
admin_bp.add_url_rule("/asignaciones/reporte/pdf", view_func=admin_controller.assignments_report_pdf, methods=["GET"])
admin_bp.add_url_rule("/asignaciones/reporte/edecanes/pdf", view_func=admin_controller.exposition_usher_report_pdf, methods=["GET"])
admin_bp.add_url_rule("/asignaciones/reporte/edecanes/excel", view_func=admin_controller.exposition_usher_report_excel, methods=["GET"])
admin_bp.add_url_rule("/asignaciones/reporte/excel", view_func=admin_controller.assignments_report_excel, methods=["GET"])
admin_bp.add_url_rule("/asignaciones/reporte/presencial", view_func=admin_controller.judge_presence_report_excel, methods=["GET"])
admin_bp.add_url_rule("/jueces/evaluacion", view_func=admin_controller.judge_pool_page, methods=["GET"])
admin_bp.add_url_rule("/jueces/evaluacion/reporte/excel", view_func=admin_controller.judges_report_excel, methods=["GET"])
admin_bp.add_url_rule("/jueces/evaluacion/pendientes/excel", view_func=admin_controller.pending_evaluations_report_excel, methods=["GET"])
admin_bp.add_url_rule("/jueces", view_func=admin_controller.judges_page, methods=["GET"])
admin_bp.add_url_rule("/usuarios/<int:judge_id>/suplantar", view_func=admin_controller.impersonate_user, methods=["POST"])
admin_bp.add_url_rule("/permisos", view_func=admin_controller.permissions_page, methods=["GET"])
admin_bp.add_url_rule("/categorias", view_func=admin_controller.categories_page, methods=["GET"])
admin_bp.add_url_rule("/campanas", view_func=admin_controller.campaigns_page, methods=["GET"])
admin_bp.add_url_rule("/academico", view_func=admin_controller.academic_page, methods=["GET"])
admin_bp.add_url_rule("/rubricas", view_func=admin_controller.rubrics_page, methods=["GET"])
admin_bp.add_url_rule("/proyectos", view_func=admin_controller.projects_page, methods=["GET"])
admin_bp.add_url_rule("/proyectos/<int:project_id>/estado", view_func=admin_controller.toggle_project_active_api, methods=["POST"])
admin_bp.add_url_rule("/recintos", view_func=admin_controller.venues_page, methods=["GET", "POST"])
admin_bp.add_url_rule("/recintos/mapa/imprimir", view_func=admin_controller.venues_print_map, methods=["GET"])
admin_bp.add_url_rule("/proyectos/reporte/excel", view_func=admin_controller.projects_report_excel, methods=["GET"])
admin_bp.add_url_rule("/tutores", view_func=admin_controller.tutors_page, methods=["GET"])
admin_bp.add_url_rule("/tutores/reporte/excel", view_func=admin_controller.tutors_report_excel, methods=["GET"])
admin_bp.add_url_rule("/logistica/pendientes/reporte.xlsx", view_func=admin_controller.logistics_pending_report_excel, methods=["GET"])
admin_bp.add_url_rule("/requerimientos", view_func=admin_controller.requirements_page, methods=["GET"])
admin_bp.add_url_rule("/proyectos/recordatorio", view_func=admin_controller.logistics_reminder_page, methods=["GET"])
admin_bp.add_url_rule("/evaluaciones", view_func=admin_controller.evaluations_page, methods=["GET"])
admin_bp.add_url_rule("/evaluaciones/acta-ganadores.docx", view_func=admin_controller.winners_acta_download, methods=["GET"])
admin_bp.add_url_rule("/documentos", view_func=admin_controller.documents_page, methods=["GET"])
admin_bp.add_url_rule("/reportes", view_func=admin_controller.reports_page, methods=["GET"])
admin_bp.add_url_rule("/reportes/respuestas-detce", view_func=admin_controller.detce_forms_report, methods=["GET"])
admin_bp.add_url_rule("/reportes/matriz-institucional.xlsx", view_func=admin_controller.institutional_matrix_excel, methods=["GET"])
admin_bp.add_url_rule("/actas/proyecto/<int:project_id>", view_func=admin_controller.evaluation_report_project_preview, methods=["GET"])
admin_bp.add_url_rule("/actas/proyecto/<int:project_id>/pdf", view_func=admin_controller.evaluation_report_project_pdf, methods=["GET"])
admin_bp.add_url_rule("/actas/proyecto/<int:project_id>/descargar", view_func=admin_controller.evaluation_report_project_download, methods=["GET"])
admin_bp.add_url_rule("/actas/general", view_func=admin_controller.evaluation_report_all_preview, methods=["GET"])
admin_bp.add_url_rule("/actas/general/pdf", view_func=admin_controller.evaluation_report_all_pdf, methods=["GET"])
admin_bp.add_url_rule("/actas/general/descargar", view_func=admin_controller.evaluation_report_all_download, methods=["GET"])
admin_bp.add_url_rule("/actas/juez/<int:judge_id>", view_func=admin_controller.evaluation_report_judge_preview, methods=["GET"])
admin_bp.add_url_rule("/actas/juez/<int:judge_id>/pdf", view_func=admin_controller.evaluation_report_judge_pdf, methods=["GET"])
admin_bp.add_url_rule("/actas/juez/<int:judge_id>/descargar", view_func=admin_controller.evaluation_report_judge_download, methods=["GET"])
admin_bp.add_url_rule("/certificados/participacion", view_func=admin_controller.participation_certificates_preview, methods=["GET"])
admin_bp.add_url_rule("/certificados/participacion/pdf", view_func=admin_controller.participation_certificates_pdf, methods=["GET"])
admin_bp.add_url_rule("/certificados/participacion/descargar", view_func=admin_controller.participation_certificates_download, methods=["GET"])
admin_bp.add_url_rule("/certificados/ganadores", view_func=admin_controller.winner_certificates_preview, methods=["GET"])
admin_bp.add_url_rule("/certificados/ganadores/pdf", view_func=admin_controller.winner_certificates_pdf, methods=["GET"])
admin_bp.add_url_rule("/certificados/ganadores/descargar", view_func=admin_controller.winner_certificates_download, methods=["GET"])
admin_bp.add_url_rule("/certificados/proyecto/<int:project_id>", view_func=admin_controller.project_certificates_preview, methods=["GET"])
admin_bp.add_url_rule("/certificados/proyecto/<int:project_id>/pdf", view_func=admin_controller.project_certificates_pdf, methods=["GET"])
admin_bp.add_url_rule("/certificados/proyecto/<int:project_id>/descargar", view_func=admin_controller.project_certificates_download, methods=["GET"])
admin_bp.add_url_rule("/smtp", view_func=admin_controller.smtp_page, methods=["GET"])
admin_bp.add_url_rule("/institucion", view_func=admin_controller.institution_page, methods=["GET"])
admin_bp.add_url_rule("/mantenimiento", view_func=admin_controller.maintenance_page, methods=["GET"])
admin_bp.add_url_rule("/base-datos", view_func=admin_controller.database_page, methods=["GET"])
admin_bp.add_url_rule("/base-datos/respaldos/<path:filename>/descargar", view_func=admin_controller.database_backup_download, methods=["GET"])
admin_bp.add_url_rule("/git", view_func=admin_controller.gitops_page, methods=["GET"])
admin_bp.add_url_rule("/dependencias", view_func=admin_controller.dependencies_page, methods=["GET"])
admin_bp.add_url_rule("/estadisticas/estudiantes", view_func=admin_controller.students_stats_page, methods=["GET"])
admin_bp.add_url_rule("/bitacora", view_func=admin_controller.logs_page, methods=["GET"])
